In [49]:

from  problem import get_train_data

data_train, labels_train = get_train_data()
data_train.head()




participants_site participants_sex  participants_age  \
subject_id                                                                   
1932355398536124106                   5                F          9.301370   
5174041730092253771                  19                M         29.000000   
10219322676643534800                 19                F         45.000000   
10645466564919190227                  5                F          9.216438   
14512541342641936232                 28                M         15.050000   

                      anatomy_lh_bankssts_area  \
subject_id                                       
1932355398536124106                      977.0   
5174041730092253771                     1279.0   
10219322676643534800                     926.0   
10645466564919190227                     983.0   
14512541342641936232                    1488.0   

                      anatomy_lh_caudalanteriorcingulate_area  \
subject_id                                                      
1932355398536124106                                     427.0   
5174041730092253771                                     730.0   
10219322676643534800                                    446.0   
10645466564919190227                                    588.0   
14512541342641936232                                    593.0   

                      anatomy_lh_caudalmiddlefrontal_area  \
subject_id                                                  
1932355398536124106                                1884.0   
5174041730092253771                                2419.0   
10219322676643534800                               1897.0   
10645466564919190227                               2479.0   
14512541342641936232                               2309.0   

                      anatomy_lh_cuneus_area  anatomy_lh_entorhinal_area  \
subject_id                                                                 
1932355398536124106                   1449.0                       463.0   
5174041730092253771                   1611.0                       467.0   
10219322676643534800                  2135.0                       570.0   
10645466564919190227                  1312.0                       525.0   
14512541342641936232                  1829.0                       726.0   

                      anatomy_lh_fusiform_area  \
subject_id                                       
1932355398536124106                     2790.0   
5174041730092253771                     3562.0   
10219322676643534800                    3064.0   
10645466564919190227                    3766.0   
14512541342641936232                    3720.0   

                      anatomy_lh_inferiorparietal_area     ...       \
subject_id                                                 ...        
1932355398536124106                             4091.0     ...        
5174041730092253771                             5380.0     ...        
10219322676643534800                            4834.0     ...        
10645466564919190227                            5091.0     ...        
14512541342641936232                            5432.0     ...        

                      anatomy_select  \
subject_id                             
1932355398536124106                1   
5174041730092253771                1   
10219322676643534800               1   
10645466564919190227               1   
14512541342641936232               1   

                                                           fmri_basc064  \
subject_id                                                                
1932355398536124106   ./data/fmri/basc064/1932355398536124106/run_1/...   
5174041730092253771   ./data/fmri/basc064/5174041730092253771/run_1/...   
10219322676643534800  ./data/fmri/basc064/10219322676643534800/run_1...   
10645466564919190227  ./data/fmri/basc064/10645466564919190227/run_1...   
14512541342641936232  ./data/fmri/basc064/14512541342641936232/run_1...   

                                                   

In [47]:
print(labels_train)

[0 0 1 ... 0 1 0]


In [6]:
print('num of subjects in training tests:{} '.format(labels_train.size))

num of subjects in training tests:1127 


In [6]:
data_train_participants= data_train[[col for col in data_train.columns if col.startswith('participants')]]
data_train_participants.head()

participants_site participants_sex  participants_age
subject_id                                                                
1932355398536124106                   5                F          9.301370
5174041730092253771                  19                M         29.000000
10219322676643534800                 19                F         45.000000
10645466564919190227                  5                F          9.216438
14512541342641936232                 28                M         15.050000

In [7]:
data_train_anatomy = data_train[[col for col in data_train.columns if col.startswith('anatomy')]]
data_train_anatomy.head()
X=data_train.drop(['participants_sex'], axis=1)
X1=X.drop(['fmri_basc064'], axis=1)
X2=X1.drop(['fmri_basc122'], axis=1)
X3=X2.drop(['fmri_basc197'], axis=1)
X4=X3.drop(['fmri_craddock_scorr_mean'], axis=1)
X5=X4.drop(['fmri_harvard_oxford_cort_prob_2mm'], axis=1)
X6=X5.drop(['fmri_msdl'], axis=1)
X7=X6.drop(['fmri_power_2011'], axis=1)
X8=X7.drop(['fmri_motions'], axis=1)
X9=X8.drop(['fmri_select'], axis=1)
X_train= X9.drop(['anatomy_select'], axis=1)
print(X_train)















                      participants_site  participants_age  \
subject_id                                                  
1932355398536124106                   5          9.301370   
5174041730092253771                  19         29.000000   
10219322676643534800                 19         45.000000   
10645466564919190227                  5          9.216438   
14512541342641936232                 28         15.050000   
7424332414628877016                   0         22.000000   
4084002381481689753                  16         10.840000   
3573738674348564622                   5          9.471233   
14016759976745635145                 22         15.000000   
7497336720738382888                  11         12.000000   
13381056719830046628                 12         13.166667   
6941346962720199636                   9         12.000000   
7466150067722601755                  30         13.000000   
710332206452811913                    0         22.000000   
13404470288245579984    

In [11]:
data_train_anatomy['anatomy_select'].head()

subject_id
1932355398536124106     1
5174041730092253771     1
10219322676643534800    1
10645466564919190227    1
14512541342641936232    1
Name: anatomy_select, dtype: int64

In [34]:
data_train_functional = data_train[[col for col in data_train.columns if col.startswith('fmri')]]
data_train_functional.head()

fmri_basc064  \
subject_id                                                                
1932355398536124106   ./data/fmri/basc064/1932355398536124106/run_1/...   
5174041730092253771   ./data/fmri/basc064/5174041730092253771/run_1/...   
10219322676643534800  ./data/fmri/basc064/10219322676643534800/run_1...   
10645466564919190227  ./data/fmri/basc064/10645466564919190227/run_1...   
14512541342641936232  ./data/fmri/basc064/14512541342641936232/run_1...   

                                                           fmri_basc122  \
subject_id                                                                
1932355398536124106   ./data/fmri/basc122/1932355398536124106/run_1/...   
5174041730092253771   ./data/fmri/basc122/5174041730092253771/run_1/...   
10219322676643534800  ./data/fmri/basc122/10219322676643534800/run_1...   
10645466564919190227  ./data/fmri/basc122/10645466564919190227/run_1...   
14512541342641936232  ./data/fmri/basc122/14512541342641936232/run_1...   

                                                           fmri_basc197  \
subject_id                                                                
1932355398536124106   ./data/fmri/basc197/1932355398536124106/run_1/...   
5174041730092253771   ./data/fmri/basc197/5174041730092253771/run_1/...   
10219322676643534800  ./data/fmri/basc197/10219322676643534800/run_1...   
10645466564919190227  ./data/fmri/basc197/10645466564919190227/run_1...   
14512541342641936232  ./data/fmri/basc197/14512541342641936232/run_1...   

                                               fmri_craddock_scorr_mean  \
subject_id                                                                
1932355398536124106   ./data/fmri/craddock_scorr_mean/19323553985361...   
5174041730092253771   ./data/fmri/craddock_scorr_mean/51740417300922...   
10219322676643534800  ./data/fmri/craddock_scorr_mean/10219322676643...   
10645466564919190227  ./data/fmri/craddock_scorr_mean/10645466564919...   
14512541342641936232  ./data/fmri/craddock_scorr_mean/14512541342641...   

                                      fmri_harvard_oxford_cort_prob_2mm  \
subject_id                                                                
1932355398536124106   ./data/fmri/harvard_oxford_cort_prob_2mm/19323...   
5174041730092253771   ./data/fmri/harvard_oxford_cort_prob_2mm/51740...   
10219322676643534800  ./data/fmri/harvard_oxford_cort_prob_2mm/10219...   
10645466564919190227  ./data/fmri/harvard_oxford_cort_prob_2mm/10645...   
14512541342641936232  ./data/fmri/harvard_oxford_cort_prob_2mm/14512...   

                                                           fmri_motions  \
subject_id                                                                
1932355398536124106   ./data/fmri/motions/1932355398536124106/run_1/...   
5174041730092253771   ./data/fmri/motions/5174041730092253771/run_1/...   
10219322676643534800  ./data/fmri/motions/10219322676643534800/run_1...   
10645466564919190227  ./data/fmri/motions/10645466564919190227/run_1...   
14512541342641936232  ./data/fmri/motions/14512541342641936232/run_1...   

                                                              fmri_msdl  \
subject_id                                                                
1932355398536124106   ./data/fmri/msdl/1932355398536124106/run_1/193...   
5174041730092253771   ./data/fmri/msdl/5174041730092253771/run_1/517...   
10219322676643534800  ./data/fmri/msdl/10219322676643534800/run_1/10...   
10645466564919190227  ./data/fmri/msdl/10645466564919190227/run_1/10...   
14512541342641936232  ./data/fmri/msdl/14512541342641936232/run_1/14...   

                                                        fmri_power_2011  \
subject_id                                                                
1932355398536124106   ./data/fmri/power_2011/1932355398536124106/run...   
5174041730092253771   ./data/fmri/power_2011/5174041730092253771/run...   
10219322676643534800  ./data/fmri/power_2011/10219322676643534800/ru...   
10

In [32]:


data_train_functional['fmri_select'].head()

subject_id
1932355398536124106     1
5174041730092253771     1
10219322676643534800    1
10645466564919190227    1
14512541342641936232    1
Name: fmri_select, dtype: int64

In [50]:
from problem import get_test_data
data_test, labels_test = get_test_data()
data_test.head()
#data_test_functional = data_test[[col for col in data_train.columns if col.startswith('fmri')]]
#data_test_functional.head()
Y=data_test.drop(['participants_sex'], axis=1)
Y1=Y.drop(['fmri_basc064'], axis=1)
Y2=Y1.drop(['fmri_basc122'], axis=1)
Y3=Y2.drop(['fmri_basc197'], axis=1)
Y4=Y3.drop(['fmri_craddock_scorr_mean'], axis=1)
Y5=Y4.drop(['fmri_harvard_oxford_cort_prob_2mm'], axis=1)
Y6=Y5.drop(['fmri_msdl'], axis=1)
Y7=Y6.drop(['fmri_power_2011'], axis=1)
Y8=Y7.drop(['fmri_motions'], axis=1)
Y9=Y8.drop(['fmri_select'], axis=1)
Y_test= Y9.drop(['anatomy_select'], axis=1)
Y_test.shape



fmri_basc064  \
subject_id                                                                
5181409268393785348   ./data/fmri/basc064/5181409268393785348/run_1/...   
8797865049371315550   ./data/fmri/basc064/8797865049371315550/run_1/...   
6486385878325245147   ./data/fmri/basc064/6486385878325245147/run_1/...   
17126438435398394588  ./data/fmri/basc064/17126438435398394588/run_1...   
16638049522113999228  ./data/fmri/basc064/16638049522113999228/run_1...   

                                                           fmri_basc122  \
subject_id                                                                
5181409268393785348   ./data/fmri/basc122/5181409268393785348/run_1/...   
8797865049371315550   ./data/fmri/basc122/8797865049371315550/run_1/...   
6486385878325245147   ./data/fmri/basc122/6486385878325245147/run_1/...   
17126438435398394588  ./data/fmri/basc122/17126438435398394588/run_1...   
16638049522113999228  ./data/fmri/basc122/16638049522113999228/run_1...   

                                                           fmri_basc197  \
subject_id                                                                
5181409268393785348   ./data/fmri/basc197/5181409268393785348/run_1/...   
8797865049371315550   ./data/fmri/basc197/8797865049371315550/run_1/...   
6486385878325245147   ./data/fmri/basc197/6486385878325245147/run_1/...   
17126438435398394588  ./data/fmri/basc197/17126438435398394588/run_1...   
16638049522113999228  ./data/fmri/basc197/16638049522113999228/run_1...   

                                               fmri_craddock_scorr_mean  \
subject_id                                                                
5181409268393785348   ./data/fmri/craddock_scorr_mean/51814092683937...   
8797865049371315550   ./data/fmri/craddock_scorr_mean/87978650493713...   
6486385878325245147   ./data/fmri/craddock_scorr_mean/64863858783252...   
17126438435398394588  ./data/fmri/craddock_scorr_mean/17126438435398...   
16638049522113999228  ./data/fmri/craddock_scorr_mean/16638049522113...   

                                      fmri_harvard_oxford_cort_prob_2mm  \
subject_id                                                                
5181409268393785348   ./data/fmri/harvard_oxford_cort_prob_2mm/51814...   
8797865049371315550   ./data/fmri/harvard_oxford_cort_prob_2mm/87978...   
6486385878325245147   ./data/fmri/harvard_oxford_cort_prob_2mm/64863...   
17126438435398394588  ./data/fmri/harvard_oxford_cort_prob_2mm/17126...   
16638049522113999228  ./data/fmri/harvard_oxford_cort_prob_2mm/16638...   

                                                           fmri_motions  \
subject_id                                                                
5181409268393785348   ./data/fmri/motions/5181409268393785348/run_1/...   
8797865049371315550   ./data/fmri/motions/8797865049371315550/run_1/...   
6486385878325245147   ./data/fmri/motions/6486385878325245147/run_1/...   
17126438435398394588  ./data/fmri/motions/17126438435398394588/run_1...   
16638049522113999228  ./data/fmri/motions/16638049522113999228/run_1...   

                                                              fmri_msdl  \
subject_id                                                                
5181409268393785348   ./data/fmri/msdl/5181409268393785348/run_1/518...   
8797865049371315550   ./data/fmri/msdl/8797865049371315550/run_1/879...   
6486385878325245147   ./data/fmri/msdl/6486385878325245147/run_1/648...   
17126438435398394588  ./data/fmri/msdl/17126438435398394588/run_1/17...   
16638049522113999228  ./data/fmri/msdl/16638049522113999228/run_1/16...   

                                                        fmri_power_2011  \
subject_id                                                                
5181409268393785348   ./data/fmri/power_2011/5181409268393785348/run...   
8797865049371315550   ./data/fmri/power_2011/8797865049371315550/run...   
6486385878325245147   ./data/fmri/power_2011/6486385878325245147/run...   
17

In [51]:

y = labels_train
y.shape


    


(1127,)

In [119]:
#classifier
#randomforest classifier 

import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn import model_selection, datasets, svm
#from sklearn import datasets, linear_model, model_selection, svm
from sklearn.ensemble import RandomForestClassifier


print (X_train.shape, labels_train.shape)
print (Y_test.shape, labels_test.shape)







(1127, 209) (1127,)
(23, 209) (23,)


In [120]:
lm= LinearRegression()
model= lm.fit(X_train, labels_train)
predictions = lm.predict(Y_test)


In [121]:
predictions[:5]




array([0.19444118, 0.82825479, 0.71556681, 0.54207726, 0.25200204])

In [123]:
model.score(Y_test, labels_test)




-0.08924576007228158

In [141]:
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(X_train, labels_train)







RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [143]:
clf.predict(Y_test)


array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0], dtype=int64)

In [145]:
clf.predict_proba(Y_test)[0:10]


array([[0.6, 0.4],
       [0.6, 0.4],
       [0.7, 0.3],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.6, 0.4],
       [0.4, 0.6],
       [0.7, 0.3],
       [0.7, 0.3],
       [0.3, 0.7]])

In [150]:
preds = clf.predict(Y_test)

pd.crosstab(labels_test, preds, rownames=['Actual asd'], colnames=['Predicted asd'])



Predicted asd  0  1
Actual asd         
0              7  4
1              8  4

In [156]:
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score

print ("Train Accuracy :: ", accuracy_score(labels_train, clf.predict(X_train)))
print ("Test Accuracy  :: ", accuracy_score(labels_test, preds))
print ("Train roc_auc_score :: ", roc_auc_score(labels_train, clf.predict(X_train)))
print ("Test roc_auc_score  :: ", roc_auc_score(labels_test, preds))
print (" Confusion matrix ", confusion_matrix(labels_test, preds))






Train Accuracy ::  0.9866903283052352
Test Accuracy  ::  0.4782608695652174
Train roc_auc_score ::  0.986200801691759
Test roc_auc_score  ::  0.4848484848484848
 Confusion matrix  [[7 4]
 [8 4]]


In [158]:
#features ranking to see important features
#print (sorted(zip(map(lambda x: round(x, 4), clf.feature_importances_), features), 
             #reverse=True))

[(0.0147, 'lh_lateralorbitofrontal_thickness'), (0.014, 'EstimatedTotalIntraCranialVol'), (0.0129, 'lh_superiorparietal_area'), (0.0127, 'lh_lateraloccipital_thickness'), (0.012, 'lh_middletemporal_area'), (0.0109, 'CSF'), (0.0107, 'Left-Inf-Lat-Vent'), (0.0106, 'rh_caudalanteriorcingulate_area'), (0.0103, 'rh_paracentral_thickness'), (0.0101, 'rh_parahippocampal_thickness'), (0.0099, 'rh_superiorfrontal_thickness'), (0.0099, '4th-Ventricle'), (0.0096, 'rh_frontalpole_thickness'), (0.0092, 'rh_insula_thickness'), (0.0092, 'lh_supramarginal_thickness'), (0.0091, 'CC_Posterior'), (0.009, 'lh_entorhinal_thickness'), (0.0088, 'Right-Hippocampus'), (0.0087, 'rh_rostralanteriorcingulate_area'), (0.0087, 'lh_bankssts_area'), (0.0086, 'lh_paracentral_thickness'), (0.0085, 'Right-Inf-Lat-Vent'), (0.0084, 'lh_inferiorparietal_thickness'), (0.0084, 'lhSurfaceHoles'), (0.0081, 'CortexVol'), (0.008, 'rh_fusiform_thickness'), (0.008, 'lh_frontalpole_thickness'), (0.0078, 'rh_transversetemporal_area'